server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

s3:
  packages:
    name: "alpha-archipelago-packages"

dynamodb:
  packages_latest:
    name: "packages.latest.alpha"
  packages_builds:
    name: "packages.builds.alpha"
  packages:
    name: "packages.alpha"

aws:
  region: "us-west-2"
  access:
    id: "AKIARDAF5R4OERLSQXOW"
    key: "uGN1m4pb+cjoXdVLzn9mVL5VLLdlNeXvuyZVVGHY"